language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-25.0.2
    - android-25
    
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew
